### ISSUE TITLE
Readme Files

### ISSUE THREAD

**Issue by johnwargo** [Kinoma/KPR-examples#65]
How about adding some readme files to the repo as well as the individual projects. At least some little bit of documentation would be useful rather than just providing source code and nothing else.

**Comment by lprader** [comment]
There is a collection of tutorials for several of the samples in the [tutorials folder](https://github.com/Kinoma/KPR-examples/tree/master/tutorials) of this repo. The [basic sensor tutorials](https://github.com/Kinoma/KPR-examples/tree/master/tutorials/basic-sensors) within that will be useful if you're just getting started and are interested in adding external hardware components to your projects.

Other KinomaJS documentation can be found in the [kinomajs repository](https://github.com/kinoma/kinomajs). There you can find full reference documentation and tutorials on defining user interfaces, networking, media, etc.

**Comment by johnwargo** [comment]
Your response doesn't seem to address my issue in any way. I'm suggesting you include instructions, a readme file, with each project so viewers can have some context and direction on how to use the sample project. Your response suggests that there are tutorials, which I already know. 

It's a common practice to include a readme file that describes the project and provides instructions for the project's use - in all of the sample app folders I looked at, there was nothing, absolutely nothing, that would help me understand what the sample project is, what it does, how it works, how to use it and so on.  See what I mean?  Help me, don't just give me code.

**Comment by lprader** [comment]
I mentioned the tutorials because they provide setup instructions and code walkthroughs for the corresponding samples (as a readme does), but I apologize that they aren't what you are asking for.

Like you said, the folders for each sample only contain source code. But all of the samples are described in the readme of the repository itself. The readme is used to populate the lists in the Samples app on Kinoma Create and the Samples tab in Kinoma Code. The source code is then downloaded by clicking/tapping a button on that list.

We use this format because it works well for a typical user of our platform. Most of our users download the samples from Kinoma Code or Kinoma Create, rather than downloading directly from GitHub. And most prefer to look at documentation/tutorials and only use the samples to understand app structure or as very basic starting points for their own projects.

So while a readme in each sample folder might be useful to some, there is no plan to add them at this time.
